#!/usr/bin/env bash
#
# Upgrade Payara on Rocky Linux
#
# Alan Franco
# github.com/fzappa/rocky-dataverse
#
# License: GPL-3.0
#
#

PAYARA_DIR="/usr/local/payara5"
DOMAIN="domain1"
BACKUP_DIR="/home/dataverse/backup/$DOMAIN"
VERSION_TO_UPGRADE="5.2021.6"
DATAVERSE_VERSION="5.11"
PROXY_SERVER="nginx"


PAYARA_SERVICE="https://guides.dataverse.org/en/$DATAVERSE_VERSION/_downloads/c08a166c96044c52a1a470cc2ff60444/payara.service"

# Colours
RED='\e[0;31m'
REDB='\e[1;31;5m'
GREEN='\e[1;92m'
YELLOW='\e[1;33m'
NC='\e[0m' # No Color

upgrade_payara(){

    echo -e "${YELLOW}Upgrade Payara to version $VERSION_TO_UPGRADE...${NC}"

    echo -e "${YELLOW}Download Payara $VERSION_TO_UPGRADE...${NC}"
    cd /opt
    wget -c https://s3-eu-west-1.amazonaws.com/payara.fish/Payara+Downloads/$VERSION_TO_UPGRADE/payara-$VERSION_TO_UPGRADE.zip
    unzip payara-$VERSION_TO_UPGRADE.zip
        
    systemctl stop $PROXY_SERVER

    echo -e "${YELLOW}Stop and backup domain $DOMAIN...${NC}"
    sudo -u dataverse $PAYARA_DIR/bin/asadmin stop-domain $DOMAIN
    mkdir -p $BACKUP_DIR
    $PAYARA_DIR/bin/asadmin backup-domain --backupDir $BACKUP_DIR $DOMAIN

    systemctl stop payara

    echo -e "${YELLOW}Installing new Payara...${NC}"
    mv /usr/local/payara5 /usr/local/payara5-old
    mv /opt/payara5 /usr/local

    chown -R root:root /usr/local/payara5
    chown dataverse /usr/local/payara5/glassfish/lib
    chown -R dataverse:dataverse /usr/local/payara5/glassfish/domains/$DOMAIN

    echo -e "${YELLOW}Start new Payara $VERSION_TO_UPGRADE...${NC}"

    cd /usr/lib/systemd/system/
    rm -rf payara.service
    wget -c $PAYARA_SERVICE
    sed -i "/^User=.*/a Group=dataverse" payara.service
    echo -e "${GREEN}Start and enable Payara service...${NC}"
    systemctl daemon-reload
    systemctl enable --now payara.service
    sudo -u dataverse $PAYARA_DIR/bin/asadmin stop-domain $DOMAIN

    $PAYARA_DIR/bin/asadmin restore-domain --backupdir $BACKUP_DIR $DOMAIN
    
    chown -R dataverse:dataverse /usr/local/payara5/glassfish/domains/$DOMAIN
    sudo -u dataverse $PAYARA_DIR/bin/asadmin start-domain $DOMAIN

    systemctl start $PROXY_SERVER

}

#excludepkgs=java-11-openjdk,java-11-openjdk-headless,postgresql,postgresql-server



main(){
    upgrade_payara
}



main





